version: '3'

tasks:
  # Check setup
  hello:
    cmds:
      - hatch run hello
  # Environemnt tasks
  up:
    cmds:
      - docker-compose -f ./docker-compose/docker-compose-postgres.yml -p notes-postgres up -d
  down:
    cmds:
      - docker-compose -p notes-postgres down
      - rm -rf ./docker-compose/.tmp
  # Database tasks
  db-up:
    cmds:
      - hatch run alembic-upgrade
  db-down:
    cmds:
      - hatch run alembic-downgrade
  db-revision:
    cmds:
      - hatch run alembic-revision {{.CLI_ARGS}}